name: Auto Commit Build Artifact

permissions:
  contents: write
  packages: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Test on deno and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    strategy:
      matrix:
        os: [
            #
            ubuntu-latest,
            # windows-latest,
            # macOS-latest,
          ]

    steps:
      - run: git config --global core.autocrlf false

      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: Run build
        run: deno task build:deno

      - name: "codecov coverage"
        uses: codecov/codecov-action@v4
        with:
          files: coverage/lcov.info

      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: "dist"
          # Whether to push the commit and, if any, its tags to the repo. It can also be used to set the git push arguments (see the paragraph below for more info)
          # Default: true
          push: true
          default_author: github_actions
          committer_name: GitHub Actions
          committer_email: actions@github.com
          message: "🚨 Commit Build Artifact from GitHub Actions"
