name: CI

permissions:
  contents: read
  packages: write

on:
  push:
  workflow_dispatch:

env:
  IMAGE_TAG: ${{ github.ref_name }}
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build-image:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runtime: deno
          - runtime: node
          - runtime: bun
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/${{ matrix.runtime }}.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ startsWith(github.ref, 'refs/tags/v') }}
          provenance: false
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}_${{ matrix.runtime }}
            ${{ env.IMAGE_NAME }}:${{ matrix.runtime }}
  biome-ci-check:
    name: biome check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome CLI
        uses: biomejs/setup-biome@v2
      - name: Run Biome
        run: biome ci .
